---
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

## Bar Plot with Counts Example

### `geom_bar()` Counts for You

From this stack overflow post <https://stackoverflow.com/questions/26553526/how-to-add-frequency-count-labels-to-the-bars-in-a-bar-graph-using-ggplot2>

```{r, fig.width = 3, fig.height = 3}
ggplot(iris, aes(x = Species)) +
  geom_bar(aes(fill = Species), color = 'black') +
# adds the counts
# The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0 and it now
# uses after_stat(count) instead
  geom_text(stat = 'count', aes(label = after_stat(count)), vjust = -1) +
# might need to adjust the plot area so the counts are nicely visible
  coord_cartesian(ylim = c(0, 55)) +
  theme_classic() +
  theme(legend.position = 'none')
```

<br>

### Dodged Bar Plot Counts

```{r}
iris %>%
# add a dummy variable so you can use fill to dodge on species
  mutate(dummy_variable = 'dummy_variable') %>%
  
ggplot(aes(x = dummy_variable, fill = Species)) +
  geom_bar(color = 'black', position = 'dodge') +
# adds the counts
  geom_text(stat = 'count', aes(label = after_stat(count)), vjust = -1,
# add position_dodge() so that the counts are spaced evenly, may need to play
# with value
            position = position_dodge(width = 0.9)) +
# might need to adjust the plot area so the counts are nicely visible
  coord_cartesian(ylim = c(0, 55)) +
  theme_classic() +
  theme(legend.position = 'none')
```

<br>

### With Pre-Computed Counts

Count the species in iris.

```{r}
iris %>%
  count(Species) -> iris_count
```

```{r, fig.width = 3, fig.height = 3}
### geom_col()
ggplot(iris_count, aes(x = Species, y = n)) +
  geom_col(aes(fill = Species), color = 'black') +
# adds the counts
  geom_text(aes(label = n), vjust = -1) +
# might need to adjust the plot area so the counts are nicely visible
  coord_cartesian(ylim = c(0, 55)) +
  labs(y = 'count') +
  theme_classic() +
  theme(legend.position = 'none')

### geom_bar()
ggplot(iris_count, aes(x = Species, y = n)) +
  geom_bar(aes(fill = Species), color = 'black', stat = 'identity') +
# adds the counts
  geom_text(aes(label = n), vjust = -1) +
# might need to adjust the plot area so the counts are nicely visible
  coord_cartesian(ylim = c(0, 55)) +
  labs(y = 'count') +
  theme_classic() +
  theme(legend.position = 'none')
```



