---
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(viridis)
library(conflicted)
library(cowplot)

filter <- dplyr::filter

knitr::opts_chunk$set(echo = TRUE)
```

## Implement Upset Plot with `ggplot()`



### Simulate Data

We're going to fake some methylation data to play with.

```{r}
set.seed(42)
tibble(site = 1:100,
       condition1 = c(rbinom(25, size = 100, prob = 0.1),
                      rbinom(50, size = 100, prob = 0.5),
                      rbinom(25, size = 100, prob = 0.8)),
       condition2 = c(rbinom(10, size = 100, prob = 0.1),
                      rbinom(10, size = 100, prob = 0.2),
                      rbinom(10, size = 100, prob = 0.3),
                      rbinom(10, size = 100, prob = 0.4),
                      rbinom(10, size = 100, prob = 0.5),
                      rbinom(10, size = 100, prob = 0.6),
                      rbinom(10, size = 100, prob = 0.7),
                      rbinom(10, size = 100, prob = 0.8),
                      rbinom(10, size = 100, prob = 0.9),
                      rbinom(10, size = 100, prob = 0.1)),
       condition3 = c(rbinom(25, size = 100, prob = 0.1),
                      rbinom(75, size = 100, prob = 0.9))) -> fake_data
```

### Plot Main Bars

```{r}
fake_data %>%
  mutate(c1_hypo = ifelse(condition1 < 20, 1, 0),
         c1_hyper = ifelse(condition1 > 80, 1, 0),
         c2_hypo = ifelse(condition2 < 20, 1, 0),
         c2_hyper = ifelse(condition2 > 80, 1, 0),
         c3_hypo = ifelse(condition3 < 20, 1, 0),
         c3_hyper = ifelse(condition3 > 80, 1, 0)) -> fake_data_coded 
```

```{r}
fake_data_coded %>%
  mutate(code_hypo = factor(case_when(c1_hypo == 1 & c2_hypo == 1 & c3_hypo == 1 ~ '123',
                               c1_hypo == 1 & c2_hypo == 1 & c3_hypo == 0 ~ '12',
                               c1_hypo == 1 & c2_hypo == 0 & c3_hypo == 1 ~ '13',
                               c1_hypo == 0 & c2_hypo == 1 & c3_hypo == 1 ~ '23',
                               c1_hypo == 1 & c2_hypo == 0 & c3_hypo == 0 ~ '1',
                               c1_hypo == 0 & c2_hypo == 1 & c3_hypo == 0 ~ '2',
                               c1_hypo == 1 & c2_hypo == 1 & c3_hypo == 0 ~ '3',
                               c1_hypo == 0 & c2_hypo == 0 & c3_hypo == 0 ~ '0'),
                            levels = c('123', '12', '13', '23', '1', '2', '3', '0')),
         code_hyper = case_when(c1_hyper == 1 & c2_hyper == 1 & c3_hyper == 1 ~ '123',
                               c1_hyper == 1 & c2_hyper == 1 & c3_hyper == 0 ~ '12',
                               c1_hyper == 1 & c2_hyper == 0 & c3_hyper == 1 ~ '13',
                               c1_hyper == 0 & c2_hyper == 1 & c3_hyper == 1 ~ '23',
                               c1_hyper == 1 & c2_hyper == 0 & c3_hyper == 0 ~ '1',
                               c1_hyper == 0 & c2_hyper == 1 & c3_hyper == 0 ~ '2',
                               c1_hyper == 1 & c2_hyper == 1 & c3_hyper == 0 ~ '3')) %>%
  filter(code_hypo != '0') %>%
ggplot(aes(x = code_hypo)) +
  geom_bar() +
  scale_x_discrete(drop = F) +
  geom_text(stat='count', aes(label=..count..), vjust=-1) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) -> bar
```

```{r}
fake_data_coded %>%
  mutate(code_hypo = factor(case_when(c1_hypo == 1 & c2_hypo == 1 & c3_hypo == 1 ~ '123',
                               c1_hypo == 1 & c2_hypo == 1 & c3_hypo == 0 ~ '12',
                               c1_hypo == 1 & c2_hypo == 0 & c3_hypo == 1 ~ '13',
                               c1_hypo == 0 & c2_hypo == 1 & c3_hypo == 1 ~ '23',
                               c1_hypo == 1 & c2_hypo == 0 & c3_hypo == 0 ~ '1',
                               c1_hypo == 0 & c2_hypo == 1 & c3_hypo == 0 ~ '2',
                               c1_hypo == 1 & c2_hypo == 1 & c3_hypo == 0 ~ '3',
                               c1_hypo == 0 & c2_hypo == 0 & c3_hypo == 0 ~ '0'),
                            levels = c('123', '12', '13', '23', '1', '2', '3', '0')),
         code_hyper = case_when(c1_hyper == 1 & c2_hyper == 1 & c3_hyper == 1 ~ '123',
                               c1_hyper == 1 & c2_hyper == 1 & c3_hyper == 0 ~ '12',
                               c1_hyper == 1 & c2_hyper == 0 & c3_hyper == 1 ~ '13',
                               c1_hyper == 0 & c2_hyper == 1 & c3_hyper == 1 ~ '23',
                               c1_hyper == 1 & c2_hyper == 0 & c3_hyper == 0 ~ '1',
                               c1_hyper == 0 & c2_hyper == 1 & c3_hyper == 0 ~ '2',
                               c1_hyper == 1 & c2_hyper == 1 & c3_hyper == 0 ~ '3')) %>%
  filter(code_hypo != '0') %>%
  gather(anno, is_obs, c1_hypo:c3_hyper) %>%
  filter(str_detect(anno, 'hypo')) %>%
  mutate(anno2 = ifelse(is_obs == 1, anno, NA)) %>%
  select(code_hypo, anno2) %>%
  na.omit() %>%
ggplot(aes(x = code_hypo, y = anno2)) +
  geom_point(size = 5) +
  geom_line(aes(group = code_hypo), size = 2) +
  scale_x_discrete(drop = F) +
  theme_minimal() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank()) -> points
```

```{r}
fake_data_coded %>%
  gather(anno, is_obs, c1_hypo:c3_hyper) %>%
  filter(str_detect(anno, 'hypo'), is_obs == 1) %>%
  na.omit() %>%

ggplot(aes(x = anno)) +
  geom_bar() +
  scale_x_discrete(position = 'top') +
  scale_y_reverse() +
  coord_flip() +
  theme_classic() +
  theme(axis.title.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.line.y = element_blank()) -> set_bar
```

```{r}
ggdraw() +
  draw_plot(bar, x = 0.2, y = 0.25, width = 0.75, height = 0.75) +
  draw_plot(points, x = 0.16, y = 0, width = 0.75, height = 0.25) +
  draw_plot(set_bar + theme(axis.title.x = element_blank()), 
            x = 0, y = 0, width = 0.25, height = 0.25)
```


