---
output: html_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

# How to summarize a long column into a shorter delimiter separated column by/convert a grouped column into vectors

Suggestion of using `paste()` to collapse from this Stack Overflow post <https://stackoverflow.com/questions/64835471/how-do-you-use-dplyrpull-to-convert-grouped-a-colum-into-vectors>
How to not include NAs while using `paste()` from this Stack Overflow post <https://stackoverflow.com/questions/13673894/suppress-nas-in-paste>

```{r}
# library(tidyverse)
tibble(fav_movies = c("The Departed", "The Green Mile", "IT", "Spirit", "The  Irishman",
                      "Titanic", "The Shawshank  Redemption", NA_character_,
                      "The Godfather", "Pulp  Fiction"),
       people = rep(c("Dave", "Mike", "Josh"), c(5, 3, 2))) -> mov_data

# combine long table into delimited vector in column
mov_data  %>%
  group_by(people) %>%
  summarize(fav_movies = paste(fav_movies, collapse = ",")) %>%
  ungroup()

# with NAs removed
mov_data  %>%
  group_by(people) %>%
  # use T/F vector generated by !is.na(COL_NAME) to subset out any NAs
  summarize(fav_movies = paste(fav_movies[!is.na(fav_movies)], collapse = ",")) %>%
  ungroup()
```

