---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Formatting Numbers Prettily in R



```{r}
numbers <- c(10000, 100000, 1000000, 
             1.57, 25.42, 15.04573, 
             0.05, 0.05671, 0.000000027)
```

#### `round()`

`round()` is a very simple `base` function to round your numbers

```{r}
### by default, round() rounds to the nearest whole number, but you can specify 
### the number of decimal points to round to using the digits argument
numbers[4:9]
round(numbers[4:9])
round(numbers[4:9], digits = 2)

### If you ask round() to round large numbers, it converts them to scientific
### notation
numbers[1:3]
round(numbers[1:3])
# It doesn't work for all these different numbers, but if you specify a number
# of digits, everything will sort of be converted to scientific notation, but
# BE CAREFUL, notice that the very small decimals are still given as 0
round(numbers)
round(numbers, digits = 1)

### can also use floor() and ceiling() to round everything down or up to the
### nearest whole number
# notice how the decimals get rounded to 0 or 1
numbers[4:9]
floor(numbers[4:9])
ceiling(numbers[4:9])
```

#### `formatC()`

`formatC()` is a `base` function for formatting numbers according to C specifications. For my purpose, it can add commas to large numbers to make them easier to read and formats things in scientific notation correctly (unlike `round()`).

```{r}
### add commas
formatC(numbers, big.mark = ',')

### scientific notation
formatC(numbers, format = "e", digits = 2)
```
